import { type NextPage } from "next";
import Head from "next/head";
import AudioPlayer from "../components/AudioPlayer";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-screen h-full flex">
        <AudioPlayer />
      </main>
    </>
  );
};

export default Home;
